In [45]:
import numpy as np
import pandas as pd
originFeature = ['WKC', 'WKR', 'WRC', 'WRR', 'BKC', 'BKR', 'winstep']
trainset = pd.read_csv( open("./trainset.csv") , 
                        header = 0                  ,
                        names  = originFeature,
                       encoding="gbk"
                        )

trainset = trainset.sample(frac=1)
trainset

WKC  WKR WRC  WRR BKC  BKR   winstep
8346    b    1   f    8   b    4  fourteen
16236   d    3   c    3   f    5  thirteen
4445    d    2   d    4   h    5    eleven
11228   b    2   a    4   f    5  fourteen
4693    c    1   b    7   e    8    eleven
9249    b    2   a    3   f    3  fourteen
497     b    1   c    3   d    4      draw
13290   d    4   d    5   h    1     seven
1903    c    3   e    4   f    4      draw
18562   c    1   b    6   d    8  thirteen
11581   d    4   h    4   h    2      nine
5907    d    1   c    7   f    6   fifteen
9520    c    2   b    3   d    4  fourteen
13898   d    3   a    4   a    2       six
13933   d    1   a    6   g    1       six
7018    a    1   e    7   e    3   fifteen
18321   b    1   e    2   e    8  thirteen
17822   c    1   c    2   f    2  thirteen
15965   b    1   e    2   c    7  thirteen
15425   c    2   a    8   a    3       ten
15537   d    4   b    1   g    3       ten
7982    b    1   e    8   c    8  fourteen
8415    d    1   a    3   e    4  fourteen
10389   c    1   c    3   c    7  fourteen
7817    d    2   e    3   a    1      four
3424    d    3   a    2   f    8    eleven
6966    a    1   g    5   f    3   fifteen
8020    d    1   a    4   d    8  fourteen
16143   d    2   f    1   b    4  thirteen
19263   c    3   c    7   h    7  thirteen
...    ..  ...  ..  ...  ..  ...       ...
20167   c    2   e    4   e    6    twelve
8534    b    1   d    2   h    4  fourteen
9246    b    1   b    3   c    8  fourteen
4320    b    2   d    6   h    7    eleven
14006   d    3   h    5   a    2       six
18778   d    2   g    3   c    7  thirteen
14696   c    1   g    2   a    8       ten
15008   d    3   h    1   h    3       ten
930     d    3   d    6   d    7      draw
15741   d    3   e    4   h    6       ten
10444   c    2   g    3   d    5  fourteen
19917   d    3   a    4   c    7    twelve
15427   d    2   f    1   h    7       ten
5968    b    1   b    3   g    5   fifteen
10602   c    2   g    5   e    4  fourteen
11352   a    1   b    8   h    6  fourteen
18506   c    2   a    8   f    6  thirteen
18759   d    2   b    3   c    6  thirteen
19276   c    2   c    3   h    5  thirteen
3795    d    4   a    8   g    5    eleven
7839    d    2   b    5   b    2      four
10158   d    1   g    8   f    3  fourteen
16325   d    1   h    4   h    7  thirteen
9259    c    1   g    5   e    7  fourteen
13244   d    2   b    2   a    6     seven
8229    d    1   g    1   f    7  fourteen
4325    d    1   c    2   b    5    eleven
19667   c    1   f    5   a    8    twelve
2191    b    1   e    5   e    4      draw
7250    b    1   c    1   d    5   fifteen

[22445 rows x 7 columns]

In [5]:
# pd.DataFrame(np.array(trainset),columns  = originFeature,)
# trainset.loc[trainset['WKC'] == 'a']
# a = pd.concat([trainset['WKC'],trainset['winstep']],axis=1)
# a.drop(columns  ='winstep')
# a.values.unique()
# pd.DataFrame(np.array(trainset['winstep']))[0]
a = trainset['winstep']
a.unique()
# trainset['winstep'][1]
# for i in range(trainset.shape[0]):
#     print(trainset.iloc[i])
#     print(i)
#     input()
# a = trainset['winstep'] 
# a == 'draw'
# a.replace([True,False],[1,-1])
# len(trainset['winstep'].values)

array(['draw', 'eight', 'eleven', 'fifteen', 'five', 'four', 'fourteen',
       'nine', 'one', 'seven', 'six', 'sixteen', 'ten', 'thirteen',
       'three', 'twelve', 'two', 'zero'], dtype=object)

In [6]:
# a = np.array([1,2,3,1])
# a.count(1)
# a = {1:'a'}
# a[1]
a = [1,2]
a.append(3)
a.index(max(a))

2

In [7]:
a = np.mat([1,2])
a * a.T + 3.3

matrix([[8.3]])

In [8]:
np.multiply(np.array([1,2,3,4,5]), np.array([1,2,3,4,5]))

array([ 1,  4,  9, 16, 25])

In [9]:
max(2.2,3.3)

3.3

In [10]:
np.nonzero((np.array([1,2,3,-2,3]) > 0) * (np.array([1,-2,3,-2,3]) > 0))

(array([0, 2, 4], dtype=int64),)

In [11]:
np.mat(np.zeros((5, 1)))

matrix([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [12]:
2500 * 6.89 * 2

34450.0

In [21]:
np.power(9,2)

81

In [40]:
from collections import Counter
a = pd.Series(np.array([1,2,3,-2,3]))
# max(np.count(a))
word_counts = Counter(a)
word_counts.most_common(1)[0][1]

2

In [46]:
np.shape([[1,2],[3,4]])

(2, 2)

In [53]:
a = np.array([1,2])
b = np.array([3,4])
np.append(a,b)
a

array([1, 2])

In [58]:
107730/17955

6.0

In [73]:
# np.mean([0.5348066298342542	,0.5334806629834254	,0.5383425414364641	,0.5239779005524862	,0.5312707182320442	])
# np.mean([0.5348066298342542	,0.5334806629834254	,0.5383425414364641	,0.5239779005524862	,0.5312707182320442		])
# np.mean([0.6296132596685083	,0.6218784530386741	,0.6209944751381216	,0.6161325966850829	,0.6165745856353592		])
# np.mean([0.6775690607734807	,0.6738121546961326	,0.6735911602209945	,0.6702762430939226	,0.6689502762430939		])
# np.mean([0.7080662983425414	,0.6941436464088397	,0.6965745856353591	,0.7007734806629834	,0.6983425414364641		])
# np.mean([0.7116022099447514	,0.7085082872928177	,0.7049723756906078	,0.7149171270718232	,0.7102762430939227		])
# np.mean([0.7160220994475138	,0.7069613259668508	,0.7043093922651934	,0.7129281767955801	,0.7173480662983427		])
# np.mean([0.7104972375690609	,0.6990055248618785	,0.7040883977900553	,0.7076243093922651	,0.7155801104972375		])
# np.mean([0.7071823204419889	,0.6943646408839779	,0.703646408839779	,0.7009944751381215	,0.7093922651933702		])
# np.mean([0.7043093922651934	,0.6983425414364641	,0.6956906077348066	,0.6970165745856354	,0.7003314917127071		])
np.mean([0.7023204419889503	,0.6892817679558011	,0.6932596685082872	,0.6928176795580111	,0.698121546961326		])

0.695160220994475