In [2]:
import numpy as np
import pandas as pd
originFeature = ['WKC', 'WKR', 'WRC', 'WRR', 'BKC', 'BKR', 'winstep']
trainset = pd.read_csv( open("./trainset.csv") , 
                        header = 0                  ,
                        names  = originFeature,
                       encoding="gbk"
                        )

In [27]:
# pd.DataFrame(np.array(trainset),columns  = originFeature,)
# trainset.loc[trainset['WKC'] == 'a']
# a = pd.concat([trainset['WKC'],trainset['winstep']],axis=1)
# a.drop(columns  ='winstep')
# a.values.unique()
# pd.DataFrame(np.array(trainset['winstep']))[0]
a = trainset['winstep']
a.unique()
# trainset['winstep'][1]
# for i in range(trainset.shape[0]):
#     print(trainset.iloc[i])
#     print(i)
#     input()
# a = trainset['winstep'] 
# a == 'draw'
# a.replace([True,False],[1,-1])
# len(trainset['winstep'].values)

array(['draw', 'eight', 'eleven', 'fifteen', 'five', 'four', 'fourteen',
       'nine', 'one', 'seven', 'six', 'sixteen', 'ten', 'thirteen',
       'three', 'twelve', 'two', 'zero'], dtype=object)

In [29]:
# a = np.array([1,2,3,1])
# a.count(1)
# a = {1:'a'}
# a[1]
a = [1,2]
a.append(3)
a.index(max(a))

2

In [49]:
a = np.mat([1,2])
a * a.T + 3.3

matrix([[8.3]])

In [56]:
np.multiply(np.array([1,2,3,4,5]), np.array([1,2,3,4,5]))

array([ 1,  4,  9, 16, 25])

In [59]:
max(2.2,3.3)

3.3

In [65]:
np.nonzero((np.array([1,2,3,-2,3]) > 0) * (np.array([1,-2,3,-2,3]) > 0))

(array([0, 2, 4], dtype=int64),)

In [67]:
np.mat(np.zeros((5, 1)))

matrix([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [71]:
2500 * 6.89 * 2

34450.0